#!/usr/bin/env bash
# Auto-generated by src/compile.py — do not edit manually.
set -euo pipefail

REPO="mistakenot/skills"
AGENTS="claude-code codex"

usage() {
  cat <<EOF
Usage: ./install.sh [OPTIONS]

Install skills from mistakenot/skills.

Options:
  --module <name>   Install only skills from a specific module.
                    Available modules: planning-workflow, ideation, maintenance, exploration, rich-docs, reflection
  --agent <agents>  Override target agents (default: claude-code codex).
                    Use '*' for all agents.
  -h, --help        Show this help message.

Examples:
  ./install.sh                              # Install all skills
  ./install.sh --module planning-workflow   # Install only planning skills
  ./install.sh --agent claude-code          # Install all skills to claude-code only
EOF
  exit 0
}

MODULE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --module)
      MODULE="$2"
      shift 2
      ;;
    --agent)
      AGENTS="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

if [[ -z "$MODULE" ]]; then
  npx skills add "$REPO" -s '*' -a $AGENTS -y
else
  case "$MODULE" in
    planning-workflow)
      SKILLS="v1-new-task,v1-new-solution,v1-new-plan,v1-review-task,v1-request-codex-review,v1-request-claude-review,v1-resolve-comments,v1-commit-task,v1-execute-task,v1-delegate-task,v1-executor-status-check,v1-address-feedback,v1-complete-task,v1-code-review,v1-task-feedback-analyser"
      ;;
    ideation)
      SKILLS="generate-10-ideas,fan-out-user-simulation"
      ;;
    maintenance)
      SKILLS="revise-readme"
      ;;
    exploration)
      SKILLS="tech-spike"
      ;;
    rich-docs)
      SKILLS="planning-doc"
      ;;
    reflection)
      SKILLS="learning-diary"
      ;;
    *)
      echo "Unknown module: $MODULE" >&2
      echo "Available modules: planning-workflow, ideation, maintenance, exploration, rich-docs, reflection" >&2
      exit 1
      ;;
  esac
  npx skills add "$REPO" -s "$SKILLS" -a $AGENTS -y
fi
