#!/usr/bin/env bash
# Auto-generated by src/compile.py — do not edit manually.
set -euo pipefail

REPO="mistakenot/skills"
TARGETS="claude,agents"

usage() {
  cat <<EOF
Usage: ./install.sh [OPTIONS]

Install skills from mistakenot/skills using \`auto skill\`.

Options:
  --module <name>    Install only skills from a specific module.
                     Available modules: planning-workflow, ideation, maintenance, handoff, exploration, rich-docs, reflection, assurance, research, domain-modelling, grill-me, eval-engineer, discovery
  --target <styles>  Comma-separated output targets (default: claude,agents).
  -h, --help         Show this help message.

Examples:
  ./install.sh                              # Install all skills
  ./install.sh --module planning-workflow   # Install only planning skills
  ./install.sh --target claude              # Install to .claude/skills only

Requires the \`auto\` CLI: https://github.com/mistakenot/auto
EOF
  exit 0
}

MODULE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --module)
      MODULE="$2"
      shift 2
      ;;
    --target)
      TARGETS="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

if ! command -v auto >/dev/null 2>&1; then
  echo "error: 'auto' not found on PATH." >&2
  echo "Install it first: https://github.com/mistakenot/auto" >&2
  exit 1
fi

# auto resolves output targets from project config, not per-command flags, so
# the project must be initialised before adding anything.
if [[ ! -f .auto/skills/skills.yaml ]]; then
  auto skill init --project --target "$TARGETS" -y
fi

# Non-interactive shells (CI, curl | bash) can't answer the trust prompt.
TRUST=()
if [[ ! -t 0 ]]; then
  TRUST=(--trust-requested)
fi

if [[ -z "$MODULE" ]]; then
  auto skill add "$REPO" --skill '*' "${TRUST[@]}"
else
  case "$MODULE" in
    planning-workflow)
      SKILLS="new-epic,new-task,new-solution,new-plan,review-task,request-codex-review,request-claude-review,request-grok-review,request-council-review,resolve-comments,commit-task,execute-task,delegate-task,delegate,status-report,address-feedback,complete-task,code-review,task-feedback-analyser"
      ;;
    ideation)
      SKILLS="generate-10-ideas,fan-out-user-simulation"
      ;;
    maintenance)
      SKILLS="revise-readme"
      ;;
    handoff)
      SKILLS="handoff"
      ;;
    exploration)
      SKILLS="tech-spike"
      ;;
    rich-docs)
      SKILLS="rich-doc"
      ;;
    reflection)
      SKILLS="learning-diary,playbook-observe,playbook-refine,playbook-search"
      ;;
    assurance)
      SKILLS="assurance-strategist"
      ;;
    research)
      SKILLS="borrow-from-oss"
      ;;
    domain-modelling)
      SKILLS="domain-modelling"
      ;;
    grill-me)
      SKILLS="grill-me"
      ;;
    eval-engineer)
      SKILLS="eval-engineer"
      ;;
    discovery)
      SKILLS="extract-demand-from-customer-conversation"
      ;;
    *)
      echo "Unknown module: $MODULE" >&2
      echo "Available modules: planning-workflow, ideation, maintenance, handoff, exploration, rich-docs, reflection, assurance, research, domain-modelling, grill-me, eval-engineer, discovery" >&2
      exit 1
      ;;
  esac
  IFS=',' read -ra SKILL_ARRAY <<< "$SKILLS"
  ARGS=()
  for S in "${SKILL_ARRAY[@]}"; do
    ARGS+=(--skill "$S")
  done
  auto skill add "$REPO" "${ARGS[@]}" "${TRUST[@]}"
fi
