#!/usr/bin/env bash
# Auto-generated by src/compile.py — do not edit manually.
set -euo pipefail

REPO="mistakenot/skills"
AGENTS="claude-code codex"

usage() {
  cat <<EOF
Usage: ./install.sh [OPTIONS]

Install skills from mistakenot/skills.

Options:
  --module <name>   Install only skills from a specific module.
                    Available modules: planning-workflow, ideation, maintenance, exploration
  --agent <agents>  Override target agents (default: claude-code codex).
                    Use '*' for all agents.
  -h, --help        Show this help message.

Examples:
  ./install.sh                              # Install all skills
  ./install.sh --module planning-workflow   # Install only planning skills
  ./install.sh --agent claude-code          # Install all skills to claude-code only
EOF
  exit 0
}

MODULE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --module)
      MODULE="$2"
      shift 2
      ;;
    --agent)
      AGENTS="$2"
      shift 2
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

if [[ -z "$MODULE" ]]; then
  npx skills add "$REPO" -s '*' -a $AGENTS -y
else
  case "$MODULE" in
    planning-workflow)
      SKILLS="new-task,new-solution,new-plan,review-task,request-codex-review,resolve-comments,commit-task,execute-task,delegate-task,executor-status-check,address-feedback,complete-task,code-review,task-feedback-analyser"
      ;;
    ideation)
      SKILLS="generate-10-ideas"
      ;;
    maintenance)
      SKILLS="revise-readme"
      ;;
    exploration)
      SKILLS="tech-spike"
      ;;
    *)
      echo "Unknown module: $MODULE" >&2
      echo "Available modules: planning-workflow, ideation, maintenance, exploration" >&2
      exit 1
      ;;
  esac
  npx skills add "$REPO" -s "$SKILLS" -a $AGENTS -y
fi
