#!/usr/bin/env bash
# Auto-generated by src/compile.py — do not edit manually.
#
# A friendly wrapper around `npx skills@latest` for installing the skill
# packages (bundles of related skills) from mistakenot/skills. Installed as `sk` because
# the bare `skills` name belongs to the npm CLI this delegates to.
#
#   sk ls                List available packages
#   sk add <package>     Install a package's skills ('all' for everything)
#   sk update            Update all installed skills
#
# Install:
#   curl -fsSL https://raw.githubusercontent.com/mistakenot/skills/main/sk.sh -o ~/.local/bin/sk && chmod +x ~/.local/bin/sk
#
# On every run the script self-updates from GitHub; if a newer version is
# found it is written in place and you are asked to re-run your command.
set -euo pipefail

REPO="mistakenot/skills"
SELF_URL="${SKILLS_SELF_URL:-https://raw.githubusercontent.com/mistakenot/skills/main/sk.sh}"
AGENTS="${SKILLS_AGENTS:-claude-code codex}"

PACKAGES="planning-workflow ideation maintenance exploration rich-docs reflection assurance research domain-modelling grill-me"

pkg_desc() {
  case "$1" in
    planning-workflow) echo "End-to-end AI-agent task delivery: requirements, solution, plan, review, execute, and ship features through a structured plan-to-merge workflow." ;;
    ideation) echo "Structured ideation: generate high-impact feature ideas and run synthetic user-research simulations to decide what to build next." ;;
    maintenance) echo "Documentation maintenance: keep READMEs and docs in sync with the current state of the code." ;;
    exploration) echo "De-risk ideas before building: run exploratory tech spikes that validate assumptions and stress-test approaches." ;;
    rich-docs) echo "Author rich single-file HTML planning docs with tabs, mermaid diagrams, file-change trees, and inline comment threads." ;;
    reflection) echo "Reflection loop: mine learnings into a diary, and observe→refine→search reusable task rules." ;;
    assurance) echo "Design end-to-end assurance and testing strategies for autonomous agent-built software." ;;
    research) echo "External-research skills: track open-source repos and mine their updates into a ranked backlog of ideas to borrow." ;;
    domain-modelling) echo "Build and maintain a project's ubiquitous language: a DDD glossary of canonical domain terms, kept in sync with the code." ;;
    grill-me) echo "Relentlessly interrogate a plan, design, or decision to surface assumptions and edge cases, recording the outcomes as numbered ADRs." ;;
    *) return 1 ;;
  esac
}

pkg_skills() {
  case "$1" in
    planning-workflow) echo "new-epic new-task new-solution new-plan review-task request-codex-review request-claude-review request-grok-review resolve-comments commit-task execute-task delegate-task delegate status-report address-feedback complete-task code-review task-feedback-analyser" ;;
    ideation) echo "generate-10-ideas fan-out-user-simulation" ;;
    maintenance) echo "revise-readme" ;;
    exploration) echo "tech-spike" ;;
    rich-docs) echo "planning-doc" ;;
    reflection) echo "learning-diary playbook-observe playbook-refine playbook-search" ;;
    assurance) echo "assurance-strategist" ;;
    research) echo "borrow-from-oss" ;;
    domain-modelling) echo "domain-modelling" ;;
    grill-me) echo "grill-me" ;;
    *) return 1 ;;
  esac
}

# Run a command, or just print it when SKILLS_DRY_RUN=1 (used by tests).
run() {
  if [[ "${SKILLS_DRY_RUN:-}" == "1" ]]; then
    echo "+ $*"
  else
    "$@"
  fi
}

# Absolute path to this script, resolving any symlinks.
_self_path() {
  local src="${BASH_SOURCE[0]}" dir
  while [ -h "$src" ]; do
    dir="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
    src="$(readlink "$src")"
    [[ "$src" != /* ]] && src="$dir/$src"
  done
  dir="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
  printf '%s/%s\n' "$dir" "$(basename "$src")"
}

# Fetch the latest version of this script. If it differs, overwrite self and
# exit so the user re-runs against the new version. Fails open: any problem
# (offline, no curl, not writable) silently skips the update.
self_update() {
  if [[ "${SKILLS_NO_SELFUPDATE:-}" == "1" || "${SKILLS_DRY_RUN:-}" == "1" ]]; then
    return 0
  fi
  command -v curl >/dev/null 2>&1 || return 0
  local self tmp
  self="$(_self_path)"
  [[ -w "$self" ]] || return 0
  tmp="$(mktemp)" || return 0
  if curl -fsSL "$SELF_URL" -o "$tmp" 2>/dev/null \
      && [[ -s "$tmp" ]] \
      && head -n1 "$tmp" | grep -q '^#!' \
      && ! cmp -s "$tmp" "$self"; then
    cat "$tmp" > "$self"
    rm -f "$tmp"
    echo "sk: self-updated to the latest version — please re-run your command." >&2
    exit 0
  fi
  rm -f "$tmp"
  return 0
}

usage() {
  cat <<EOF
sk — install reusable agent skill packages from $REPO

Usage:
  sk ls                 List available packages
  sk add <package>...    Install one or more packages ('all' for everything)
  sk update [args...]   Update all installed skills (default: project scope;
                        pass -g for global, -p for project, or skill names)
  sk help               Show this help

Each "package" is a bundle of related skills. Run 'sk ls' to see them.
Skills install to project-local .agents/ and .claude/ by default.
The script self-updates from GitHub on each run.

Environment:
  SKILLS_AGENTS         Target agents (default: "claude-code codex")
  SKILLS_NO_SELFUPDATE  Set to 1 to disable self-update
  SKILLS_SELF_URL       Override the URL self-update fetches from (e.g. a fork)
  SKILLS_DRY_RUN        Set to 1 to print commands instead of running them
EOF
}

cmd_ls() {
  echo "Available packages from $REPO:"
  echo
  local p
  for p in $PACKAGES; do
    printf '  %-18s %s\n' "$p" "$(pkg_desc "$p")"
  done
  echo
  echo "Install one with:  sk add <package>"
  echo "Install all with:  sk add all"
}

add_one() {
  local pkg="$1"
  if [[ "$pkg" == "all" ]]; then
    echo "==> Installing all skills from $REPO"
    run npx skills@latest add "$REPO" -s '*' -a $AGENTS -y
    return
  fi
  local list
  if ! list="$(pkg_skills "$pkg")"; then
    echo "sk add: unknown package '$pkg' (run 'sk ls')" >&2
    exit 1
  fi
  local count
  count="$(echo $list | wc -w | tr -d ' ')"
  echo "==> Installing package '$pkg' ($count skills) from $REPO"
  local s
  for s in $list; do
    run npx skills@latest add "$REPO" -s "$s" -a $AGENTS -y
  done
}

cmd_add() {
  if [[ $# -eq 0 ]]; then
    echo "sk add: missing package name (run 'sk ls')" >&2
    exit 1
  fi
  local pkg
  for pkg in "$@"; do
    add_one "$pkg"
  done
}

cmd_update() {
  # Forward extra args to `skills update`, e.g. `sk update -g` (global scope),
  # `sk update -p` (project scope), or specific skill names.
  echo "==> Updating all installed skills"
  run npx skills@latest update -y "$@"
}

main() {
  self_update

  local cmd="${1:-help}"
  if [[ $# -gt 0 ]]; then shift; fi

  case "$cmd" in
    ls|list)            cmd_ls "$@" ;;
    add|install)        cmd_add "$@" ;;
    update|upgrade)     cmd_update "$@" ;;
    help|-h|--help)     usage ;;
    *)
      echo "sk: unknown command '$cmd'" >&2
      echo >&2
      usage >&2
      exit 1
      ;;
  esac
}

main "$@"
