#!/usr/bin/env python3
"""Validate and visualise a UBIQUITOUS_LANGUAGE.md glossary.

Stdlib only — runs anywhere with python3, no install step.

Usage:
    python scripts/glossary.py check   docs/concepts/UBIQUITOUS_LANGUAGE.md
    python scripts/glossary.py diagram docs/concepts/UBIQUITOUS_LANGUAGE.md [--write]

`check`   validates structure and relationships; exit code 1 if any errors (CI-friendly).
`diagram` renders the _Has_ relationships as a mermaid flowchart; with --write it refreshes a
          marker-delimited block near the top of the glossary in place.

This is intentionally a glossary linter, not a parser of arbitrary markdown. It expects the
format described in references/language-format.md: bold term, definition, `_Avoid_:` line, and
an optional `_Has_:` line using only `one`/`many` between defined terms.
"""
import argparse
import re
import sys

TERM_RE = re.compile(r"^\*\*(?P<name>.+?)\*\*:\s*$")
META_RE = re.compile(r"^_(?P<key>\w+)_:\s*(?P<val>.*)$")
HEADING_RE = re.compile(r"^#{1,6}\s")
DIAGRAM_START = "<!-- ER-DIAGRAM:START (generated by glossary.py — do not edit by hand) -->"
DIAGRAM_END = "<!-- ER-DIAGRAM:END -->"


class Entry:
    def __init__(self, name, line_no):
        self.name = name
        self.line_no = line_no
        self.definition = []      # list of str
        self.avoid = None         # raw string after _Avoid_:  (None = line absent)
        self.has = None           # raw string after _Has_:    (None = line absent)


def parse(text):
    """Return list[Entry]. Tolerant of blank lines and multi-line definitions."""
    entries = []
    cur = None
    for i, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        m = TERM_RE.match(line)
        if m:
            cur = Entry(m.group("name").strip(), i)
            entries.append(cur)
            continue
        if HEADING_RE.match(line):
            cur = None
            continue
        if cur is None:
            continue
        meta = META_RE.match(line)
        if meta:
            key = meta.group("key").lower()
            if key == "avoid":
                cur.avoid = meta.group("val").strip()
            elif key == "has":
                cur.has = meta.group("val").strip()
            # unknown _Xxx_: lines are ignored (forward-compatible)
            continue
        if line.strip():
            cur.definition.append(line.strip())
    return entries


def _norm(s):
    return s.strip().lower()


def _depluralise(s):
    if s.endswith("ies"):
        return s[:-3] + "y"
    if s.endswith("s") and not s.endswith("ss"):
        return s[:-1]
    return s


def parse_has(val):
    """'one Customer, many Line Items' -> [('one','Customer'), ('many','Line Items')]."""
    out = []
    for part in val.split(","):
        part = part.strip()
        if not part or part == "—":
            continue
        toks = part.split(None, 1)
        if len(toks) == 2 and toks[0].lower() in ("one", "many"):
            out.append((toks[0].lower(), toks[1].strip()))
        else:
            out.append(("?", part))  # malformed cardinality
    return out


def resolve_target(target, term_norms):
    """Match a _Has_ target name to a defined term (handles plural/singular)."""
    cands = {_norm(target), _depluralise(_norm(target)), _norm(target) + "s"}
    for c in cands:
        if c in term_norms:
            return term_norms[c]
    return None


def check(path):
    text = open(path, encoding="utf-8").read()
    entries = parse(text)
    errors, warnings = [], []

    if not entries:
        errors.append("No term entries found — expected `**Term**:` blocks.")

    # canonical term registry
    seen = {}
    term_norms = {}
    for e in entries:
        n = _norm(e.name)
        if n in seen:
            errors.append(f"L{e.line_no}: duplicate term '{e.name}' (also defined at L{seen[n]}).")
        else:
            seen[n] = e.line_no
            term_norms[n] = e.name

    # per-entry structural checks
    avoided = {}  # normalised avoid word -> (owning term, line)
    for e in entries:
        if not e.definition:
            errors.append(f"L{e.line_no}: '{e.name}' has no definition.")
        if e.avoid is None:
            errors.append(f"L{e.line_no}: '{e.name}' is missing an `_Avoid_:` line "
                          f"(use `_Avoid_: —` if there are genuinely no competing words).")
        else:
            for w in e.avoid.split(","):
                w = w.strip()
                if w and w != "—":
                    avoided.setdefault(_norm(w), (e.name, e.line_no))

    # a canonical term must not appear on another term's _Avoid_ list
    for e in entries:
        if _norm(e.name) in avoided:
            owner, ln = avoided[_norm(e.name)]
            if owner != e.name:
                errors.append(f"L{e.line_no}: '{e.name}' is canonical but is also listed under "
                              f"_Avoid_ of '{owner}' (L{ln}) — pick one.")

    # _Has_ relationships must point at defined terms with valid cardinality
    for e in entries:
        if e.has is None:
            continue
        for card, target in parse_has(e.has):
            if card == "?":
                errors.append(f"L{e.line_no}: '{e.name}' _Has_ entry '{target}' must start with "
                              f"'one' or 'many'.")
                continue
            if resolve_target(target, term_norms) is None:
                errors.append(f"L{e.line_no}: '{e.name}' _Has_ '{card} {target}', but '{target}' "
                              f"is not a defined term.")
            # cheap schema-smell guard
            if re.search(r"\bid\b|0\.\.|nullable|optional|foreign key|fk\b", target, re.I):
                warnings.append(f"L{e.line_no}: '{e.name}' _Has_ '{target}' looks like schema "
                                f"detail — keep relationships conceptual (one/many between terms).")

    for w in warnings:
        print(f"warning: {w}")
    for er in errors:
        print(f"error: {er}")
    n = len(entries)
    if errors:
        print(f"\nFAIL: {len(errors)} error(s), {len(warnings)} warning(s) across {n} term(s).")
        return 1
    print(f"OK: {n} term(s) valid, {len(warnings)} warning(s).")
    return 0


def _node_id(name):
    return re.sub(r"[^A-Za-z0-9]", "_", name)


def build_diagram(path):
    text = open(path, encoding="utf-8").read()
    entries = parse(text)
    term_norms = {_norm(e.name): e.name for e in entries}
    edges = []
    nodes = {}
    for e in entries:
        if e.has is None:
            continue
        for card, target in parse_has(e.has):
            if card == "?":
                continue
            resolved = resolve_target(target, term_norms) or target
            nodes[e.name] = _node_id(e.name)
            nodes[resolved] = _node_id(resolved)
            edges.append((_node_id(e.name), card, _node_id(resolved)))
    lines = ["```mermaid", "flowchart LR"]
    for name, nid in sorted(nodes.items()):
        lines.append(f'    {nid}["{name}"]')
    for src, card, dst in edges:
        lines.append(f"    {src} -->|{card}| {dst}")
    if not edges:
        lines.append("    %% no _Has_ relationships defined yet")
    lines.append("```")
    return "\n".join(lines)


def diagram(path, write):
    block = build_diagram(path)
    if not write:
        print(block)
        return 0
    text = open(path, encoding="utf-8").read()
    wrapped = f"{DIAGRAM_START}\n{block}\n{DIAGRAM_END}"
    if DIAGRAM_START in text and DIAGRAM_END in text:
        new = re.sub(re.escape(DIAGRAM_START) + r".*?" + re.escape(DIAGRAM_END),
                     wrapped.replace("\\", "\\\\"), text, flags=re.S)
    else:
        # insert after the first paragraph following the H1 title
        lines = text.splitlines()
        insert_at = len(lines)
        seen_title = False
        for i, ln in enumerate(lines):
            if ln.startswith("# "):
                seen_title = True
                continue
            if seen_title and ln.strip() == "":
                # first blank line after title's paragraph
                if i + 1 < len(lines) and lines[i + 1].strip():
                    insert_at = i + 1
                    break
        block_lines = ["", "## Domain at a glance", "", wrapped, ""]
        lines[insert_at:insert_at] = block_lines
        new = "\n".join(lines)
    open(path, "w", encoding="utf-8").write(new if new.endswith("\n") else new + "\n")
    print(f"Wrote ER diagram into {path}")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Validate / visualise a ubiquitous-language glossary.")
    sub = ap.add_subparsers(dest="cmd", required=True)
    c = sub.add_parser("check", help="validate structure and relationships")
    c.add_argument("path")
    d = sub.add_parser("diagram", help="render _Has_ relationships as a mermaid diagram")
    d.add_argument("path")
    d.add_argument("--write", action="store_true", help="refresh the diagram block in the file")
    args = ap.parse_args()
    if args.cmd == "check":
        sys.exit(check(args.path))
    if args.cmd == "diagram":
        sys.exit(diagram(args.path, args.write))


if __name__ == "__main__":
    main()
